### ISSUE TITLE
History Viewer doesn't receive data, sometimes

### ISSUE THREAD

**Issue by adrhumphreys** [silverstripe/silverstripe-versioned-snapshot-admin#11]
Seems like it's maybe some race condition but the graphql query `snapshotQuery` will not fire sometimes when it loads. 

https://github.com/silverstripe/silverstripe-versioned-snapshot-admin/pull/10 addresses this but I'm not 100% sure it does so in the right way

**Comment by blueo** [comment]
It might be because we get both the original versioned query and then the snapshot versioned query. Whichever finishes at the 'right' time gets displayed - you can see the two graphql requests are fired on the tab load

**Comment by blueo** [comment]
https://github.com/silverstripe/silverstripe-versioned-snapshot-admin/pull/18 avoids this issue by changing the namespace used by injector
