### ISSUE TITLE
Component registration with same name

### ISSUE THREAD

**Issue by adrhumphreys** [silverstripe/silverstripe-versioned-snapshot-admin#17]
We have components from `versioned-admin` and `versioned-snapshot-admin` competing with each other to be registered.
This means under certain circumstances for example you'll get the  `versioned-admin` version of `HistoryViewerVersionList` rather than the `versioned-snapshot-admin` version

**Comment by unclecheese** [comment]
To be resolved by https://github.com/silverstripe/silverstripe-versioned-snapshot-admin/pull/18 ?

**Comment by blueo** [comment]
@unclecheese that PR will address this problem. There is still an outstanding question of whether we should rename all the components/reducer and make it completely separate or will injector support a case like this. The current PR is a half solution in that it just renames the bits that rely on injectors. So we're thinking we'd need an issue to track the end result.
