### ISSUE TITLE
Should this project diverge from versioned-admin?

### ISSUE THREAD

**Issue by adrhumphreys** [silverstripe/silverstripe-versioned-snapshot-admin#19]
Currently we've run into the issue that we are unable to unregister extensions from the injector. This means HoC's etc can replace/effect the state of your registered components.

Our resolution in the short term was to rename the references to the components so they would not be affected by versioned-admin.

This is the first step in diverging from versioned-admin and deciding that snapshot-admin is it's own module that is seperate from versioned-admin. We're in a good position now to decide if we go down this route or if we take a step back, fix the injector and continue stapling this on top of versioned-admin.

What this requires is a road map for the project. What it's aiming to achieve in the long term, and how we will get there.

I guess this is the discussion for that

**Comment by unclecheese** [comment]
I think the ideal outcome would be that Versioned takes on the snapshot functionality as core, and snapshot admin eventually "merges" into versioned-admin. Admittedly, the way we have things set up now, that would be anything but a clean merge.

However, assuming the idea of snapshots is viable and we get to a point where it's largely bug-free, it's hard to envision a scenario where versioned-admin continues to be marketable. I see snapshots as a wholesale replacement for the status-quo versioned functionality.

There's also a ton of stuff that they share right now, specifically the detail view. You could argue that this module is just versioned-admin with more information in the list view.
