### ISSUE TITLE
Docs for versioned DataObjects

### ISSUE THREAD

**Issue by kinglozzer** [silverstripe/silverstripe-versioned-snapshot-admin#33]
README currently says:

> Provides a drop-in replacement UI for versioned-admin that adds snapshots to the history view.

Which implies that if you have `versioned-admin` set up and working, this module won’t need any additional configuration. That might be true for page history, but it’s not true for versioned DataObjects.

I had to update:

- How the components are registered with `Injector.transform()` as the component names are different
- The graphql query itself so it fetches `SnapshotHistory` instead of `Versions`

**Comment by unclecheese** [comment]
Hey, Loz. Since you're an early adopter, can you confirm that this is mitigated by the new "History viewer anywhere" feature? https://github.com/silverstripe/silverstripe-versioned-snapshot-admin#history-view----anywhere

**Comment by kinglozzer** [comment]
Yep, it is 😁
