### ISSUE TITLE
Support for CMS Admin 1.8

### ISSUE THREAD

**Issue by ssmarco** [silverstripe/silverstripe-versioned-snapshot-admin#62]
I tried installing this on latest CMS 4.8 but got few errors below:
```
- silverstripe/versioned-snapshot-admin 0.1.0 requires silverstripe/admin < 1.7
...
-  Installation request for silverstripe/admin (locked at 1.8.0) -> satisfiable by silverstripe/admin[1.8.0]
```
Any advise in supporting 4.8?

**Comment by brynwhyman** [comment]
Looks like the constraint was removed v0.2.0. Give that a go?

**Comment by ssmarco** [comment]
> Looks like the constraint was removed v0.2.0. Give that a go?

Thanks @brynwhyman
