### ISSUE TITLE
Test suite failing because of a warning

### ISSUE THREAD

**Issue by mfendeksilverstripe** [silverstripe/silverstripe-versioned-snapshot-admin#85]
# Test suite failing because of a warning

The test suite is failing because the following warning is issues during the test suite.

```
No tests found in class "SilverStripe\Dev\SapphireTest"
```

The test run triggers this warning on Travis but also on local. It doesn't seem to be related to PHPUnit version either.

## Travis run

```
PHPUnit 9.5.20 #StandWithUkraine
1340
1341Warning:       Your XML configuration validates against a deprecated schema.
1342Suggestion:    Migrate your XML configuration using "--migrate-configuration"!
1343
1344.W                                                                  2 / 2 (100%)
1345
1346Time: 00:03.842, Memory: 118.50 MB
1347
1348There was 1 warning:
1349
13501) Warning
1351No tests found in class "SilverStripe\Dev\SapphireTest".
1352
1353phpvfscomposer:///home/travis/build/silverstripe/silverstripe-versioned-snapshot-admin/vendor/phpunit/phpunit/phpunit:97
1354/home/travis/build/silverstripe/silverstripe-versioned-snapshot-admin/vendor/bin/phpunit:115
1355
1356WARNINGS!
1357Tests: 2, Assertions: 1, Warnings: 1.
1358The command "if [[ "$PHPUNIT_TEST" != "" && "$PHPUNIT_SUITE" == "" ]]; then vendor/bin/phpunit --fail-on-warning; fi" exited with 1.
```

## Local run

```
vagrant@vanilla:/var/www/mysite/www$ php vendor/bin/phpunit vendor/silverstripe/versioned-snapshot-admin/tests/ flush=all
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

.W                                                                  2 / 2 (100%)

Time: 14.01 seconds, Memory: 148.50MB

There was 1 warning:

1) Warning
No tests found in class "SilverStripe\Dev\SapphireTest".

/var/www/mysite/www/vendor/sminnee/phpunit/phpunit:51
/var/www/mysite/www/vendor/bin/phpunit:102

WARNINGS!
Tests: 2, Assertions: 1, Warnings: 1.
```

I did some initial investigation but I couldn't really find anything obvious. The PHPUnit configuration is identical to the [Versioned snapshots](https://github.com/silverstripe/silverstripe-versioned-snapshots) module which runs its test suite just fine.

We can still see that the regular test pass so it's not a blocker for development but we should try to fix this soon.

**Comment by GuySartorelli** [comment]
Doesn't explain why the problem isn't occurring in the other module, but looking at the [Upgrading to PHPUnit 9.5 for PHP8 support](https://docs.silverstripe.org/en/4/upgrading/phpunit9/#common-changes-to-make-to-your-unit-test-suites) docs, the `<testsuite>` tag should be wrapped in `<testsuites>`

**Comment by mfendeksilverstripe** [comment]
The local run I posted uses PHP Unit 5 and still has the same problem so it's likely unrelated. I can still try it out though.

**Comment by mfendeksilverstripe** [comment]
Closing this as this is working in https://github.com/silverstripe/silverstripe-versioned-snapshot-admin/pull/86
